# Generated by Django 3.0.8 on 2020-09-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etcoption',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
